from typing import Protocol, Optional
from app.domain.entities import Usuario, Reporte


class UsuarioRepository(Protocol):
    def get_by_id(self, user_id: str) -> Optional[Usuario]: ...
    def update_me(self, user_id: str, telefono: Optional[str], comuna_id: Optional[int]) -> Usuario: ...


class ReporteRepository(Protocol):
    def get_by_id(self, reporte_id: str) -> Optional[Reporte]: ...
    def list_by_usuario(self, usuario_id: str, limit: int, cursor: Optional[str]) -> tuple[list[Reporte], Optional[str]]: ...
    def list_by_comuna(self, comuna_id: int, limit: int, cursor: Optional[str], estado: Optional[str]) -> tuple[list[Reporte], Optional[str]]: ...
